# database
app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/blubo
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    pool-size: 30
  upload:
    dir: ${user.home}/blubo/backend/files/books
spring:
  flyway:
    baseline-on-migrate: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
